development:
  system:
    domain: localhost
    start_page_url: /admin/user/list
    cms_name: Lolita CMS
    cms_title: Lolita CMS
    multi_domain_portal: false
    domain_depth: 0
    items_per_page: 20
    public_user_model: "Admin::PublicUser"
    public_user_table: admin_users
    flash_actions:
      - /media/image_file/new_create
      - /media/video_file/new_create
      - /media/audio_file/new_create
      - /media/simple_file/new_create
    geokit: false
  email:
    default_from: "info@example.com"
    default_to: "info@example.com"
    bugs_from: "www@example.com"
    bugs_to: "bugs@example.com"
    smtp_settings:
      tls: true
      address: "smtp.gmail.com"
      port: 587
      domain: domain.com
      user_name: "user@domain.com"
      password: "password"
      authentication: plain
  access:
    allow:
      system_in_public: true
      rewrite: false
  i18n:
    translation: true
    language_code: lv
  google:
    maps_key: false
    analytics_key: false

production:
  system:
    domain: localhost
    start_page_url: /admin/user/list
    cms_name: Lolita CMS
    cms_title: Lolita CMS
    multi_domain_portal: false
    domain_depth: 0
    items_per_page: 20
    public_user_model: "Admin::PublicUser"
    public_user_table: admin_users
    flash_actions:
      - /picture/new_create
      - /video_file/new_create
      - /audio_file/new_create
      - /file/new_create
    geokit: false
  email:
    default_from: "info@example.com"
    default_to: "info@example.com"
    bugs_from: "www@example.com"
    bugs_to: "bugs@example.com"
    smtp_settings:
      tls: true
      address: "smtp.gmail.com"
      port: 587
      domain: domain.com
      user_name: "user@domain.com"
      password: "password"
      authentication: plain
  access:
    allow:
      system_in_public: true
      rewrite: false
  i18n:
    translation: true
    language_code: lv
  google:
    maps_key: false
    anlytics_key: false

test:
  system:
    domain: localhost
    start_page_url: /admin/user/list
    cms_name: Lolita CMS
    cms_title: Lolita CMS
    multi_domain_portal: false
    domain_depth: 0
    items_per_page: 20
    public_user_model: "Admin::PublicUser"
    public_user_table: admin_users
    flash_actions:
      - /image_file/new_create
      - /video_file/new_create
      - /audio_file/new_create
      - /simple_file/new_create
    geokit: false
  email:
    default_from: "info@example.com"
    default_to: "info@example.com"
    bugs_from: "www@example.com"
    bugs_to: "bugs@example.com"
    smtp_settings:
      tls: true
      address: "smtp.gmail.com"
      port: 587
      domain: domain.com
      user_name: "user@domain.com"
      password: "password"
      authentication: plain 
  access:
    allow:
      system_in_public: true
      rewrite: false
  i18n:
    translation: true
    language_code: lv
  google:
    maps_key: false
    anlytics_key: false
