development:
  system:
    domain: localhost
    multi_domain_portal: false
    domain_depth: 0
    items_per_page: 20
    public_user_model: "Admin::PublicUser"
    public_user_table: admin_users
    flash_actions:
      - /picture/new_create,
      - /video_file/new_create,
      - /audio_file/new_create,
      - /file/new_create
  email:
    default_from: "info@example.com"
    default_to: "info@example.com"
  access:
    allow:
      system_in_public: true
      rewrite: false
  i18n:
    translation: true
    language_code: lv
  google:
    key: false

production:
  system:
    domain: localhost
    multi_domain_portal: false
    domain_depth: 0
    items_per_page: 20
    public_user_model: "Admin::PublicUser"
    public_user_table: admin_users
    flash_actions:
      - /picture/new_create,
      - /video_file/new_create,
      - /audio_file/new_create,
      - /file/new_create
  email:
    default_from: "info@example.com"
    default_to: "info@example.com"
  access:
    allow:
      system_in_public: true
      rewrite: false
  i18n:
    translation: true
    language_code: lv
  google:
    key: false

test:
  system:
    domain: localhost
    multi_domain_portal: false
    domain_depth: 0
    items_per_page: 20
    public_user_model: "Admin::PublicUser"
    public_user_table: admin_users
    flash_actions:
      - /picture/new_create,
      - /video_file/new_create,
      - /audio_file/new_create,
      - /file/new_create
  email:
    default_from: "info@example.com"
    default_to: "info@example.com"
  access:
    allow:
      system_in_public: true
      rewrite: false
  i18n:
    translation: true
    language_code: lv
  google:
    key: false